apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-service-config
data:
  NODE_ENV: "production"
  PORT: "3003"
  USER_SERVICE_URL: "http://user-service-service:3001"
  POST_SERVICE_URL: "http://post-service-service:3002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
      - name: feed-service
        image: dgeorgiev0348/feed-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: feed-service-config
        env: 
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: feed-service-secret 
              key: JWT_SECRET 
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service-service
spec:
  selector:
    app: feed-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feed-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed-service-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70