name: Build and Deploy Feed Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-feed-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get short git hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image for feed-service
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          load: true
          tags: feed-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/feed-service:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/feed-service:cache,mode=max

      - name: Push Docker image
        run: |
          docker tag feed-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:${{ steps.vars.outputs.sha_short }}
          docker tag feed-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:latest
          
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:${{ steps.vars.outputs.sha_short }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/feed-service:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: jpeg-project
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate gcloud with service account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > "${HOME}/gcloud-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
          gcloud config set account $(gcloud auth list --filter=status:ACTIVE --format="value(account)")

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials jpeg-cluster \
            --region europe-west4 # <-- Replace with your cluster's region/zone

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/feed-service-deployment feed-service=${{ secrets.DOCKERHUB_USERNAME }}/feed-service:${{ steps.vars.outputs.sha_short }} \
            --namespace=default